# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'StoreAccount' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for StoreAccount
    pod 'Geth'

  target 'StoreAccountTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'StoreAccount-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StoreAccount-tvOS

#target 'StoreAccount-tvOSTests' do
#inherit! :search_paths
    # Pods for testing
#end

#end
